# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Censored Word Filter' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Censored Word Filter
  pod 'SwiftyJSON'
  pod 'Alamofire'
  pod 'OAuthSwift'	
  pod 'AlamofireNetworkActivityIndicator' 
end
